updates Dockerfile to support multi-arch builds
verdaccio/verdaccio pull request #2031
Opened 2020-12-15 09:57 UTC by morlay

example:  https://hub.docker.com/r/morlay/verdaccio/tags?page=1&ordering=last_updated
```
docker buildx build --push --platform=linux/amd64,linux/arm64 --tag morlay/verdaccio .
```

github actions setup 
https://github.com/docker/setup-buildx-action

2020-12-15 13:40 UTC, juanpicado commented
hi @morlay thanks for your PR. I'd need you to share some info regarding what is this about, I recall this topic was mentioned months ago, but I ignore the trade-offs of merging this. I tagged collaborators and let's wait.

2020-12-15 14:19 UTC, morlay commented
@juanpicado just want to publish verdaccio as multi arch docker image

so people could use verdaccio image in arm64 device like Apple M1

2020-12-15 14:44 UTC, morlay commented
switch to draft until whole workflow ready

2020-12-15 14:55 UTC, morlay commented
@juanpicado 
could you show me where the final workflow for publishing docker image.

i haven't found it 😂

2020-12-15 15:18 UTC, juanpicado commented
It happens directly in docker hub. We don't have this flow in GitHub actions yet.

2020-12-15 15:32 UTC, morlay commented
could i add someone by https://github.com/docker/setup-buildx-action ？

2020-12-15 17:50 UTC, juanpicado commented
I don't know yet, but what I think we cannot do is modify the Dockerifle, correct me if I'm wrong, that might break the `latest` tag. The only I know about this topic is https://www.docker.com/blog/apple-silicon-m1-chips-and-docker/ and seems pretty new.  So let's wait. We are in the holiday season 🙃  so I don't expect much movement on this in the next weeks.

2020-12-16 02:12 UTC, morlay commented
@juanpicado have a nice holiday first. I just put this PR here.

Apple M1 is one case. in fact, in cloud compute, arm marchine has raised.
some testing https://recap.dev/blog/arm-backed-servers-better-performance-for-less-money/ 

I added a publish workflow.

workflow for master branch https://github.com/morlay/verdaccio/runs/1561104741 (now as `edge` tag, could rename by `tag-custom` and `tag-custom-only` https://github.com/crazy-max/ghaction-docker-meta#inputs)
workflow for tag https://github.com/morlay/verdaccio/runs/1561107479

https://hub.docker.com/r/morlay/verdaccio/tags?page=1&ordering=last_updated

btw is image tag `4.x-next` for master branch ?

2020-12-16 07:05 UTC, juanpicado commented
> btw is image tag 4.x-next for master branch ?

Yes, exactly. 

Furthermore, during the testing phase, I publish `5.x` to GitHub packages 

https://github.com/verdaccio/verdaccio/packages/13531

but this one is not relevant yet and not recommendable to use it.

2020-12-16 07:21 UTC, morlay commented
@juanpicado got it. 

one more thing, `docker.pkg.github.com` is deprecated & not support publishing the multi-arch image.
https://docs.github.com/en/free-pro-team@latest/packages/guides/migrating-to-github-container-registry-for-docker-images

2020-12-16 07:35 UTC, morlay reviewed
@juanpicado 

only need add secrets `DOCKER_USERNAME`  and `DOCKER_PASSWORD`.
We could switch to github actions for multi-arch image publishing with same tag rule.

2020-12-16 07:35 UTC, morlay commented on .github/workflows/docker-publish.yml
> +          tag-custom-only: ${{ github.ref == 'refs/heads/master' }}
master branch should publish tag `4.x-next`

2020-12-16 07:35 UTC, morlay commented on .github/workflows/docker-publish.yml
> +      - name: Build & Push
tag rule https://github.com/crazy-max/ghaction-docker-meta#handle-semver-tag

when tag `v4.10.1`
the tag `latest` `4` `4.10`  `4.10.1` will published

2020-12-16 07:35 UTC, morlay commented on Dockerfile
> +FROM --platform=${BUILDPLATFORM:-linux/amd64} node:14.15.1-alpine as builder
limit build only run once on same arch as host

only need final image as multi-arch image.

2020-12-16 07:35 UTC, morlay commented on .github/workflows/docker-publish.yml
> +      - uses: docker/setup-qemu-action@v1
Dockerfile contains `RUN`, we need this run execute `arm64` binaries on amd64 host.

2020-12-28 06:02 UTC, juanpicado commented
> @juanpicado
> 
> only need add secrets `DOCKER_USERNAME` and `DOCKER_PASSWORD`.
> We could switch to github actions for multi-arch image publishing with same tag rule.

ok, this looks much better, let me get into it.

2020-12-28 06:06 UTC, juanpicado commented on .github/workflows/docker-publish.yml
> +      - 'pnpm-*.yaml'
master branch uses yarn, in this case would be `yarn.lock`. Remember the master branch structure is completely difference, this looks like you took it from the branch `5.x`. At this point we want only cover `master === 4.x`.

2020-12-28 17:11 UTC, juanpicado reviewed
After some testing it works pretty fine :+1: 
![docker1](https://user-images.githubusercontent.com/558752/103231445-10930980-4938-11eb-9d68-b51a2a6d1fa6.png)

2020-12-28 17:21 UTC, juanpicado commented on .github/workflows/docker-publish.yml
> +      - 'pnpm-*.yaml'
```
  push:
    paths:
      - .github/workflows/docker-publish.yml
      - 'src/**'
      - 'conf/**'
      - 'types/**',
      - 'docker-bin/**'
      - 'bin/**' 
      - 'package.json'
      - 'yarn.lock'
```

2020-12-28 17:22 UTC, juanpicado requested changes
Small change and we can move on this :+1:

2020-12-29 01:50 UTC, morlay commented
@juanpicado updated with your suggestion.

btw. after merging, need to disable build of Docker Hub too.

2020-12-29 09:57 UTC, juanpicado approved these changes
Great work @morlay !

2020-12-29 10:00 UTC, juanpicado commented
@morlay is there anything worth mention at the documentation? anything aside of the new platform supported the users must know from now on? 

https://verdaccio.org/docs/en/docker

2020-12-29 10:01 UTC, merged

2020-12-29 10:47 UTC, juanpicado commented
There it is :) :1st_place_medal: 

![Screenshot from 2020-12-29 11-46-07](https://user-images.githubusercontent.com/558752/103278352-90b67f00-49cb-11eb-8396-e920037c44f6.png)

2020-12-30 01:48 UTC, morlay commented
> @morlay is there anything worth mention at the documentation? anything aside of the new platform supported the users must know from now on?
> 
> https://verdaccio.org/docs/en/docker

Nope. nothing need to changes. 

Multi-arch image return manifests list with platforms.
```
$ docker manifest inspect verdaccio/verdaccio:4.x-next
{
   "schemaVersion": 2,
   "mediaType": "application/vnd.docker.distribution.manifest.list.v2+json",
   "manifests": [
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 2410,
         "digest": "sha256:03ae6df781a2ea6ce733bcb7fbc5b37e1ed47d101bc7ac768ce8873e167a5053",
         "platform": {
            "architecture": "amd64",
            "os": "linux"
         }
      },
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 2410,
         "digest": "sha256:af4fc662cdbf232cf14815d53d6de58e5daa604ad79d45406f1d465017c50195",
         "platform": {
            "architecture": "arm64",
            "os": "linux"
         }
      }
   ]
}
```

when we run `docker pull`, it will return the matched digest

```bash
$ docker pull verdaccio/verdaccio:4.x-next

# on amd64 device, will be
docker pull verdaccio/verdaccio@sha256:03ae6df781a2ea6ce733bcb7fbc5b37e1ed47d101bc7ac768ce8873e167a5053

# on arm64 device, will be
docker pull verdaccio/verdaccio@sha256:af4fc662cdbf232cf14815d53d6de58e5daa604ad79d45406f1d465017c50195
```