make pinojs work pm2 in verdaccio
verdaccio/verdaccio pull request #2212
Opened 2021-04-29 19:16 UTC by amitgilad3

#2210

2021-05-01 14:25 UTC, juanpicado commented on src/lib/logger/logger.ts
> +import SonicBoom from 'sonic-boom';
This should be on the `package.json`, pnpm is quite strict in terms of dependencies are not estrictly defined.
```
└─ pino@npm:6.11.2
   └─ sonic-boom@npm:1.4.0 (via npm:^1.0.2)
```

2021-05-01 15:09 UTC, juanpicado requested changes
Unfortunately this solution does not work,

with `  - { type: file, path: verdaccio.log, level: http}` setup as logger, the `stdout` is enabled by default.

In Verdaccio 5 the logger is initialized twice (I've already fixed that in master), so Pino.js takes the default `stdout` by default and ignore the second setup call. You can check running this.

```
DEBUG=verdaccio:logger node debug/bootstrap.js
  verdaccio:logger setup logger +0ms
  verdaccio:logger logging stdout enabled +1ms
  verdaccio:logger has prettifier? true +0ms
 warn --- config file  - /home/user/.config/verdaccio/config.yaml
  verdaccio:logger setup logger +569ms
  verdaccio:logger logging file enabled +1ms
  verdaccio:logger has prettifier? true +0ms
(node:94779) Warning: deprecate: multiple logger configuration is deprecated, please check the migration guide.
(Use `node --trace-warnings ...` to show where the warning was created)
 warn --- Plugin successfully loaded: verdaccio-htpasswd
 warn --- Plugin successfully loaded: verdaccio-audit
 warn --- http address - http://localhost:4873/ - verdaccio/5.0.4
```

The log is redirected to stdout and the file is empty. 

Maybe make sense to also initialize setup only once very after the configuration has been parsed like I did here https://github.com/verdaccio/verdaccio/commit/19d272d10ec771665391c3d17c6fbe2812c27ecc

2021-05-01 15:12 UTC, juanpicado commented on src/lib/logger/logger.ts
> +import SonicBoom from 'sonic-boom';
Ignore this, we should not add `sonic-boom` dependency at all or use it as import, if Pino.js change that, then breaking change would be hard to fix.

2021-05-01 21:36 UTC, amitgilad3 commented
Thanks @juanpicado for the update, I'll look what you did and try to fix it accordingly

2023-02-25 16:52 UTC, juanpicado commented
closing this, logger not longer in 5.x branch

2023-02-25 16:52 UTC, closed without merging